#cloud-config

runcmd:
  - echo "Downloading install script"
  - curl -f -L -o /tmp/provision-cosmos-sdk-vm.sh "https://${storage_account}.blob.core.windows.net/account/bootstrapped-dotnet-installation.sh?${sas_token}"

  - dos2unix /tmp/provision-cosmos-sdk-vm.sh
  - chmod +x /tmp/provision-cosmos-sdk-vm.sh

  - echo "Running provisioning script"
  - COSMOS_ENDPOINT="${cosmos_endpoint}" COSMOS_KEY="${cosmos_key}" /bin/bash /tmp/provision-cosmos-sdk-vm.sh