---
- name: Install .NET SDK, clone repo, configure Cosmos env, and run samples
  hosts: cosmos_vm
  become: true
  gather_facts: true

  vars:
    cosmos_endpoint: "{{ cosmos_endpoint | default(omit) }}"
    cosmos_key: "{{ cosmos_key | default(omit) }}"
    dotnet_install_url: "https://dot.net/v1/dotnet-install.sh"
    dotnet_install_dir: "/usr/local/dotnet"
    cosmos_repo: "https://github.com/hardeymolhar/azure-data-platform.git"
    repo_dest: "/home/app"
    cosmos_nuget_version: "3.22.1"

  pre_tasks:
    - name: Fail if required vars are missing
      ansible.builtin.assert:
        that:
          - cosmos_endpoint is not none
          - cosmos_key is not none

  tasks:

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Download dotnet installer
      ansible.builtin.get_url:
        url: "{{ dotnet_install_url }}"
        dest: /tmp/dotnet-install.sh
        mode: "0755"

    - name: Install .NET SDK
      ansible.builtin.command:
        argv:
          - /tmp/dotnet-install.sh
          - --channel
          - "8.0"
          - --install-dir
          - "{{ dotnet_install_dir }}"
      args:
        creates: "{{ dotnet_install_dir }}/dotnet"

    - name: Clone project repository
      ansible.builtin.git:
        repo: "{{ cosmos_repo }}"
        dest: "{{ repo_dest }}"
        version: HEAD
        update: yes
        force: yes
      become_user: azureuser

    - name: Run Cosmos connection example
      ansible.builtin.shell: |
        dotnet restore
        dotnet build
        dotnet run
      args:
        chdir: "{{ repo_dest }}/sdk/01-establish-connection"
      become_user: azureuser

    - name: Run Cosmos batch example
      ansible.builtin.shell: |
        dotnet restore
        dotnet build
        dotnet run
      args:
        chdir: "{{ repo_dest }}/sdk/02-batch-inserts"
      become_user: azureuser

    - name: Run Cosmos index optimization
      ansible.builtin.shell: |
        dotnet restore
        dotnet build
        dotnet run
      args:
        chdir: "{{ repo_dest }}/sdk/03-index-optimization"
      become_user: azureuser